use QLyPhuTungXeMay
CREATE TABLE PhuTung (
    MaPT VARCHAR(10) PRIMARY KEY,
    TenPT VARCHAR(100),
    LoaiXe VARCHAR(50),
    DonViTinh VARCHAR(20),
    DonGiaNhap DECIMAL(18,2),
    DonGiaBan DECIMAL(18,2),
    SoLuongTon INT
);
CREATE TABLE NhaCungCap (
    MaNCC VARCHAR(10) PRIMARY KEY,
    TenNCC VARCHAR(100),
    DiaChi VARCHAR(200),
    DienThoai VARCHAR(15)
);
CREATE TABLE NhanVien (
    MaNV VARCHAR(10) PRIMARY KEY,
    TenNV VARCHAR(50),
    ChucVu VARCHAR(30),
    TaiKhoan VARCHAR(50),
    MatKhau VARCHAR(50),
    SDT VARCHAR(15)
);
CREATE TABLE PhieuNhap (
    MaPN VARCHAR(10) PRIMARY KEY,
    NgayNhap DATETIME,
    MaNCC VARCHAR(10),
    MaNV VARCHAR(10),
    TongTien DECIMAL(18,2),
    FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
        ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
        ON UPDATE CASCADE ON DELETE NO ACTION
);
CREATE TABLE ChiTietPhieuNhap (
    MaPN VARCHAR(10),
    MaPT VARCHAR(10),
    SoLuong INT,
    DonGiaNhap DECIMAL(18,2),
    PRIMARY KEY (MaPN, MaPT),
    FOREIGN KEY (MaPN) REFERENCES PhieuNhap(MaPN)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (MaPT) REFERENCES PhuTung(MaPT)
        ON UPDATE CASCADE ON DELETE NO ACTION
);
CREATE TABLE KhachHang (
    MaKH VARCHAR(10) PRIMARY KEY,
    TenKH VARCHAR(50),
    DienThoai VARCHAR(15),
    DiaChi VARCHAR(200),
    LoaiXe VARCHAR(50)
);
CREATE TABLE HoaDon (
    MaHD VARCHAR(10) PRIMARY KEY,
    NgayLap DATETIME,
    MaKH VARCHAR(10),
    MaNV VARCHAR(10),
    TongTien DECIMAL(18,2),
    ChietKhau DECIMAL(5,2),
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
        ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
        ON UPDATE CASCADE ON DELETE NO ACTION
);
CREATE TABLE ChiTietHoaDon (
    MaHD VARCHAR(10),
    MaPT VARCHAR(10),
    SoLuong INT,
    DonGiaBan DECIMAL(18,2),
    ThanhTien DECIMAL(18,2),
    PRIMARY KEY (MaHD, MaPT),
    FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (MaPT) REFERENCES PhuTung(MaPT)
        ON UPDATE CASCADE ON DELETE NO ACTION
);
